# Generated by Django 4.2.3 on 2023-08-03 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='Question',
            field=models.ForeignKey(default=datetime.datetime(2023, 8, 3, 19, 13, 57, 590682, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
            preserve_default=False,
        ),
    ]
